---
title: "Metadata preprocessing"
output: html_document
date: "2024-03-26"
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# Read functions & packages
source("scripts/functions/functions_utility.R")
source("scripts/functions/functions_visualization.R")
source("scripts/functions/themes_palettes.R")

# Read data
data <- 
  import_df("data/processed/olink_data/olink_data_qc.csv") |> 
  rename(Sample = SampleID) |> 
  mutate(Sample = as.character(Sample))

metadata <- import_df("data/Exports from R after processing updated data files/all_data.xlsx")

metadata <- 
  metadata |> 
  select(!starts_with("Olink")) |>
  rename(Sample = Patient_number) |> 
  filter(Sample %in% data$Sample) |> 
  mutate(ID = as.numeric(Sample), 
         Cohort = ifelse(ID > 1000, "ALLVOS", "MEDECA")) |> 
  select(-ID)

metadata_medeca <- import_df("data/2024-04-04 pat 1-728.xlsx")
metadata_allvos <- import_df("data/Cohortdata proteomics 240429 till fredrika.xlsx")
metadata_allvos_controls <- import_df("data/ALLVOS/Diagnosis Proteomics 238.xlsx")
```

# Metadata pre-processing

## MEDECA

```{r}
keep_columns <- c("Patient number", "Sex 1 male", "Age", "CUP", "Ongoing cancer known prior to DC", 
                  "Loss to follow up","Other disease than cancer", "No disease", "Autoimmune1",
                  "Inflammatory", "Infectious", "thromboembolism", "Other disease", "Metastases", 
                  "Carcinom", "Germinal cell tumors", "SCC", "Urothelial", "Neuroendocrine tumors",
                  "Adenocarcinoma", "HCC", "Kidney", "Adrenal", "Prostate", "Lung", "Breast", "Thyroid",
                  "Gynecologic","Ovarian or tubar", "Colorectal", "Urine bladder", "Merkel cell carcinoma",
                  "Small cell parotid", "Pancreas or gall bladder or bile duct", "Ventricle", 
                  "Other adenocarcinoma", "Other carcinoma such as mesothelioma", "Sarkom", "Lymfom",
                  "Melanom", "Myelom", "MDS MPN", "Other cancer")

meta_medeca <- 
  metadata_medeca |>
  select(keep_columns) |> 
  rename(Sample = `Patient number`) |> 
  mutate(`Loss to follow up` = ifelse(is.na(`Loss to follow up`), 0, `Loss to follow up`)) |>
  filter(Sample %in% data$Sample,
         `Ongoing cancer known prior to DC` == 0,
         `Loss to follow up` != 1) |> 
  mutate(Sex = ifelse(`Sex 1 male` == 1, "Male", "Female")) |> 
  select(-`Ongoing cancer known prior to DC`, -`Loss to follow up`, - `Sex 1 male`) |> 
  relocate(Sex, .after = "Age") |> 
  mutate(`No disease` = ifelse(Sample == 494, 0, `No disease`), #Correction
         `Other disease than cancer` = ifelse(Sample == "138", 1, `Other disease than cancer`), # Correction
         `No disease` = ifelse(Sample == "138", 0, `No disease`), # Correction
          Category = case_when(`Other disease than cancer` == 0 & `No disease` == 0 ~ "Cancer",
                              `Other disease than cancer` == 0 & `No disease` == 1 ~ "No diagnosis",
                              `Other disease than cancer` == 1 & `No disease` == 0 ~ "Other diseases",
                              T ~ NA),
         Disease_type = case_when(Autoimmune1 == 1 ~ "Autoimmune",
                                  Inflammatory == 1 ~ "Inflammatory", 
                                  Infectious == 1 ~ "Infectious", 
                                  thromboembolism == 1 ~ "Other", 
                                  `Other disease` == 1 ~ "Other",
                                  Category == "Other diseases" ~ "Other", #Sample 297 & 372 changed
                                  Category == "Cancer" ~ "Cancer",
                                  Category == "No diagnosis" ~ "No diagnosis"),
         Cancer = ifelse(Disease_type == "Cancer", "Yes", "No")) |>  
  select(-Autoimmune1, -Inflammatory, -Infectious, -thromboembolism) |> 
  relocate(Category, Disease_type, .after = Sex) |> 
  mutate(Sample = as.character(Sample),
         Disease_type = factor(Disease_type, 
                               levels = c("Cancer", "No diagnosis", "Autoimmune", "Infectious", "Inflammatory", "Other")),
         Category = factor(Category, 
                           levels = c("Cancer", "No diagnosis", "Other diseases")))
```

## ALLVOS 

```{r}
duplicated_allvos <- 
  metadata_allvos_controls |> 
  count(`Sample ID`) |> 
  arrange(-n) |> 
  filter(n > 1) |> 
  pull(`Sample ID`)

meta_allvos <- 
  metadata_allvos |>
  mutate(StudyID = as.character(StudyID),
         `Lost to follow up` = ifelse(is.na(`Lost to follow up`), 0, `Lost to follow up`)) |> 
  filter(`Ongoing cancer` != 1,
         `Lost to follow up` != 1,
         StudyID %in% data$Sample) |> 
  select(Sample = StudyID, Age, Sex, Cancer) |> 
  left_join(metadata_allvos_controls |>
               filter(!(`Sample ID` %in% duplicated_allvos & Category != "Cancer")) |> 
              mutate(`Sample ID` = as.character(`Sample ID`)) |> 
              select(Sample = `Sample ID`, Disease_type = Category), by = "Sample") |> 
  mutate(Cancer = ifelse(Cancer == 1, "Yes", "No"),
         Category = ifelse(Disease_type %in% c("Autoimmune", "Infectious", "Inflammatory", "Other"), "Other diseases", Disease_type),
         Disease_type = factor(Disease_type, 
                               levels = c("Cancer", "No diagnosis", "Autoimmune", "Infectious", "Inflammatory", "Other")),
         Category = factor(Category, 
                           levels = c("Cancer", "No diagnosis", "Other diseases")))

# 5 ALLVOS patients no cancer but no diagnosis
metadata_allvos |> 
    mutate(`Lost to follow up` = ifelse(is.na(`Lost to follow up`), 0, `Lost to follow up`)) |> 
  filter(!StudyID %in% metadata_allvos_controls$`Sample ID`,
         `Ongoing cancer` != 1,
         `Lost to follow up` != 1,
         StudyID %in% as.numeric(data$Sample))

metadata_allvos_controls |> 
  filter(!`Sample ID` %in% metadata_allvos$StudyID)

metadata_allvos |> 
  filter(!StudyID %in% metadata_allvos_controls$`Sample ID`)

#Check patient ID missmatch
metadata_allvos |> 
  mutate(`Lost to follow up` = ifelse(is.na(`Lost to follow up`), 0, `Lost to follow up`)) |> 
  filter(`Lost to follow up` == 0,
         `Ongoing cancer` != 1) |> 
#  distinct(StudyID) |> 
  filter(StudyID %in% as.numeric(data$Sample)) |> 
  filter(!StudyID %in% metadata_allvos_controls$`Sample ID`)

metadata_allvos_controls |>
  filter(`Sample ID` %in% duplicated_allvos)

meta_allvos |> 
  filter(is.na(Disease_type))
  #distinct(Disease_type)

```

## Combine

```{r}
meta_combined <- 
  meta_medeca |> 
  select(Sample, Age, Sex, Cancer, Category, Disease_type) |> 
  mutate(Cohort = "MEDECA") |> 
  bind_rows(meta_allvos |> 
              select(Sample, Age, Sex, Cancer, Category, Disease_type) |> 
              mutate(Cohort = "ALLVOS")) 
```

# Filter data to include only samples with metadata

```{r}
data_filtered <- 
  data |> 
  distinct(Sample) |> 
  filter(Sample %in% meta_combined$Sample) |> 
  distinct(Sample)

length(unique(data$Sample))
nrow(meta_allvos) + nrow(meta_medeca) 
nrow(meta_combined)
length(unique(data_filtered$Sample))
```

# Save data & metadata 

```{r}
dir.create("data/processed/final_data/")

write_csv(data_filtered, "data/processed/final_data/final_olink_data.csv")  
write_csv(meta_combined, "data/processed/final_data/combined_metadata.csv")  
write_csv(meta_medeca, "data/processed/final_data/medeca_metadata.csv")  
write_csv(meta_allvos, "data/processed/final_data/allvos_metadata.csv")  
```

# Overview of the cohort


## Sample distribution MEDECA/ALLVOS

```{r}
# Visualize the number of cases in both cohorts
p_right <- 
  meta_combined  |>
  group_by(Cancer) |>
  count(Cohort) |>
  ungroup() |> 
  group_by(Cohort) |> 
  mutate(cum_n = cumsum(n)) |> 
  mutate(Cancer = factor(Cancer, levels = c("Yes", "No")),
         Cohort = factor(Cohort, levels = rev(c("MEDECA", "ALLVOS")))) |>
  ggplot(aes(Cohort, n, fill = Cancer)) +
  geom_col(width = 0.5) +
  scale_fill_manual(values = pal_cancer) + 
  geom_text(aes(label = n, y = cum_n - 20), vjust = -0.5, fontface = "bold", color = "white") +
  theme_hpa() +
#  ggtitle("Cancer detection") +
  coord_flip() +
  theme(axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank())

p_left <- 
  meta_combined  |>
  group_by(Cohort) |>
  count(Sex) |>
  ungroup() |> 
  group_by(Cohort) |> 
  mutate(cum_n = cumsum(n)) |> 
  mutate(Cohort = factor(Cohort, levels = rev(c("MEDECA", "ALLVOS"))),
         Sex = factor(Sex, levels = c("Male", "Female"))) |>
  ggplot(aes(Cohort, n, fill = Sex)) + 
  geom_col(width = 0.5) +
  scale_fill_manual(values = pal_sex) + 
  geom_text(aes(label = n, y = cum_n - 20), vjust = -0.5, fontface = "bold", color = "white") +
  theme_hpa(axis_y = F) + 
  scale_y_reverse() +
  coord_flip() +
  theme(legend.position = "left")
  
p_age <- 
  meta_combined |>
  ggplot(aes(y = Cohort, x = Age, fill = Cancer)) +
  geom_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.6, show.legend = F, scale = 1) +
  scale_fill_manual(values = pal_cancer) +
  theme_hpa(axis_y = F) 
  
p_left + p_right + p_age
ggsave(savepath("cancer_detected_cohort.pdf"), h = 4, w = 12)

```

## Controls MEDECA

```{r}
meta_medeca |>  
  group_by(Category) |>
  filter(Disease_type != "Cancer") |> 
  count(Disease_type) |> 
  mutate(total = sum(n)) |> 
  ggplot(aes(Category, n, fill = Disease_type)) +
  geom_col() +
  geom_text(aes(label = total, y = total + 5)) + 
  scale_fill_manual(values = pal_group) +
  theme_hpa() +
  ggtitle("MEDECA controls") +
  xlab("")
  
#ggsave(savepath("MEDECA_controls.png"), h = 5, w = 5)

meta_medeca |>  
  filter(Disease_type != "Cancer") |> 
  group_by(Disease_type) |> 
  count() |> 
  ggplot(aes(Disease_type, n, fill = Disease_type)) +
  geom_col() +
  geom_text(aes(label = n, y = n + 5)) + 
  scale_fill_manual(values = pal_group) +
  theme_hpa(angled = T) +
  xlab("")
  
#ggsave(savepath("MEDECA_controls.pdf"), h = 5, w = 4)
```

## PCA MEDECA

```{r}
# Subset MEDECA data
data_medeca <- 
  data |> 
  filter(Sample %in% meta_medeca$Sample)

# Run PCA
pca_medeca <- 
  do_pca(data = data_medeca, 
         meta = meta_medeca,
         variable = "Disease_type", 
         wide = F,
         impute = T,
         plots = T)

pca_medeca$pca_plot 

# Manuscript figure
pca_medeca$pca_res %>%
  left_join(meta_medeca, by = "Sample") %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = Category), alpha = 0.7, size = 2, show.legend = F) +
  scale_color_manual(values = pal_group_3) +
  labs(color = NULL) +
  theme_hpa() +

meta_medeca |>
  group_by(Category, Disease_type) |> 
  count() |> 
  mutate(Disease_type = factor(Disease_type, levels = rev(levels(Disease_type)))) |> 
  ggplot(aes(Disease_type, n, fill = Category)) +
  geom_col() +
  geom_text(aes(label = n, y = n + 5)) + 
  scale_fill_manual(values = pal_group_3) +
  coord_flip() +
  theme_hpa(angled = T) +
  xlab("") +
  ylab("Number of samples")
  
ggsave(savepath("MEDECA_controls.pdf"), h = 4.5, w = 10)
```
